name: m_hike_flutter
description: M-Hike Cross-platform App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^6.0.0

  # UI Components
  cupertino_icons: ^1.0.2

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Date/Time Picker
  intl: ^0.18.1

  # State Management (optional but recommended)
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  image_picker:
  image_cropper:
  cached_network_image:
  photo_view:

  # Location and Maps
  geolocator:
  geocoding:
  permission_handler:
  vietmap_flutter_gl:
  http:

  # Share & Chart
  share_plus:
  fl_chart:
  screenshot:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true